apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: guestbook
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/component: frontend
spec:
  type: LoadBalancer
  ports:
  - nodePort: 32006
    targetPort: 80
    port: 80
    name: frontend-service
  selector:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/component: frontend
